# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ad74a8661f1c7e9bd4524a02d1d94b42298d2af349e810606631b195b9efd97112e6a42a0e5b0f2df5d8861dc1cda6dfed4c5c5b0bd25a3801a9a9e469c1f237

test:
  secret_key_base: d554b4ce99008ef54634ebbc2cc9e870ffb09dd5738368fa4a6fb96b4f53cf8a54b2c6453a377f4067393848bb9ab6573e13c9a84760c823318e31c8eb983196

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
